import json
import csv
import io
import hashlib
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from governance.redaction import RedactionEngine

MANDATORY_DISCLAIMER = (
    "This system provides confidence-scored technical associations for authorized analyst review. "
    "It does not defeat Tor, establish a person's real-world identity, or replace legal/forensic investigation."
)

class ExportSnapshot(BaseModel):
    export_id: str
    case_id: Optional[str] = None
    generated_by: str
    user_role: str
    generated_at: str
    score_model_version: str = "scoring-v1.0"
    calculation_input_hash: str
    actors: List[Dict[str, Any]] = Field(default_factory=list)
    candidate_links: List[Dict[str, Any]] = Field(default_factory=list)
    evidence_units: List[Dict[str, Any]] = Field(default_factory=list)
    limitations: List[str] = Field(default_factory=list)
    disclaimer: str = MANDATORY_DISCLAIMER

class ExportEngine:
    """
    Export Engine for reproducible case reports (EC-28, EC-35).
    Freezes exact versions of evidence units, candidate links, actors,
    score model versions, and calculation input hashes prior to rendering.
    Subsequent changes to underlying evidence/links do NOT alter the snapshot.
    Supports JSON, CSV, and PDF report formats.
    """

    def __init__(self):
        self.redaction_engine = RedactionEngine()

    def create_snapshot(
        self,
        generated_by: str,
        user_role: str,
        actors: List[Dict[str, Any]],
        candidate_links: List[Dict[str, Any]],
        evidence_units: List[Dict[str, Any]],
        case_id: Optional[str] = None,
        limitations: Optional[List[str]] = None
    ) -> ExportSnapshot:
        now = datetime.now(timezone.utc).isoformat()
        
        # 1. Sanitize evidence units based on role (EC-28)
        sanitized_evidence = [
            self.redaction_engine.sanitize_evidence_unit(ev if isinstance(ev, dict) else ev.model_dump(), user_role)
            for ev in evidence_units
        ]
        
        # 2. Convert candidate links
        sanitized_links = [
            link if isinstance(link, dict) else link.model_dump()
            for link in candidate_links
        ]

        # 3. Compute calculation input hash over sorted evidence IDs and link hashes (EC-35)
        ev_ids = sorted([ev.get("evidence_id", "") for ev in sanitized_evidence])
        link_ids = sorted([link.get("link_id", "") for link in sanitized_links])
        hash_input = f"scoring-v1.0|{','.join(ev_ids)}|{','.join(link_ids)}"
        input_hash = hashlib.sha256(hash_input.encode()).hexdigest()

        exp_hash = hashlib.sha256(f"{generated_by}_{now}_{input_hash}".encode()).hexdigest()[:12]
        export_id = f"exp_{exp_hash}"

        # 4. Aggregate limitations
        all_limitations = set(limitations or [])
        all_limitations.add("Export contains frozen snapshot of evidence and candidate links at generation time.")
        for ev in sanitized_evidence:
            for lim in ev.get("limitations", []):
                all_limitations.add(lim)

        return ExportSnapshot(
            export_id=export_id,
            case_id=case_id,
            generated_by=generated_by,
            user_role=user_role,
            generated_at=now,
            score_model_version="scoring-v1.0",
            calculation_input_hash=input_hash,
            actors=actors,
            candidate_links=sanitized_links,
            evidence_units=sanitized_evidence,
            limitations=sorted(list(all_limitations)),
            disclaimer=MANDATORY_DISCLAIMER
        )

    def render_json(self, snapshot: ExportSnapshot) -> str:
        """Renders export snapshot as formatted JSON string."""
        return json.dumps(snapshot.model_dump(), indent=2)

    def render_csv(self, snapshot: ExportSnapshot) -> str:
        """Renders candidate links and evidence units as CSV string."""
        output = io.StringIO()
        writer = csv.writer(output)

        # Header section
        writer.writerow(["SIH26151 Threat Actor Attribution Platform — Export Snapshot"])
        writer.writerow(["Export ID", snapshot.export_id])
        writer.writerow(["Generated By", snapshot.generated_by])
        writer.writerow(["User Role", snapshot.user_role])
        writer.writerow(["Generated At", snapshot.generated_at])
        writer.writerow(["Calculation Input Hash", snapshot.calculation_input_hash])
        writer.writerow([])

        # Candidate Links table
        writer.writerow(["--- Candidate Links ---"])
        writer.writerow(["Link ID", "Left Entity", "Right Entity", "Score", "Tier", "State", "Calculation Input Hash"])
        for link in snapshot.candidate_links:
            writer.writerow([
                link.get("link_id"),
                link.get("left_entity_id"),
                link.get("right_entity_id"),
                link.get("score"),
                link.get("tier"),
                link.get("state"),
                link.get("calculation_input_hash")
            ])
        writer.writerow([])

        # Evidence Units table
        writer.writerow(["--- Evidence Units ---"])
        writer.writerow(["Evidence ID", "Category", "Indicator Type", "Indicator Value", "Confidence Weight", "Independence Group", "Explanation"])
        for ev in snapshot.evidence_units:
            writer.writerow([
                ev.get("evidence_id"),
                ev.get("category"),
                ev.get("indicator_type"),
                ev.get("indicator_value"),
                ev.get("confidence_weight"),
                ev.get("independence_group_id"),
                ev.get("explanation")
            ])
        writer.writerow([])
        writer.writerow(["Disclaimer", snapshot.disclaimer])

        return output.getvalue()

    def render_pdf(self, snapshot: ExportSnapshot) -> bytes:
        """
        Renders export report as PDF bytes.
        Uses reportlab if available, or produces a structured PDF document buffer.
        """
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib import colors

            buffer = io.BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
            styles = getSampleStyleSheet()
            story = []

            title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], fontSize=16, textColor=colors.navy)
            body_style = styles['Normal']

            story.append(Paragraph("<b>SIH26151 Case Attribution Report</b>", title_style))
            story.append(Spacer(1, 10))
            story.append(Paragraph(f"<b>Export ID:</b> {snapshot.export_id} | <b>Generated By:</b> {snapshot.generated_by} ({snapshot.user_role})", body_style))
            story.append(Paragraph(f"<b>Generated At:</b> {snapshot.generated_at}", body_style))
            story.append(Paragraph(f"<b>Model Version:</b> {snapshot.score_model_version} | <b>Calculation Input Hash:</b> {snapshot.calculation_input_hash[:16]}...", body_style))
            story.append(Spacer(1, 12))

            # Disclaimer
            disc_style = ParagraphStyle('DiscStyle', parent=body_style, fontSize=8, textColor=colors.darkred)
            story.append(Paragraph(f"<b>MANDATORY DISCLAIMER:</b> {snapshot.disclaimer}", disc_style))
            story.append(Spacer(1, 12))

            # Candidate Links Table
            story.append(Paragraph("<b>Candidate Links Summary</b>", styles['Heading2']))
            link_data = [["Link ID", "Left Entity", "Right Entity", "Score", "Tier"]]
            for link in snapshot.candidate_links:
                link_data.append([
                    str(link.get("link_id")),
                    str(link.get("left_entity_id")),
                    str(link.get("right_entity_id")),
                    f"{link.get('score'):.2f}" if isinstance(link.get('score'), (int, float)) else str(link.get('score')),
                    str(link.get("tier"))
                ])
            t = Table(link_data)
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
                ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
                ('FONTSIZE', (0,0), (-1,-1), 9),
            ]))
            story.append(t)
            story.append(Spacer(1, 14))

            # Evidence Units
            story.append(Paragraph("<b>Evidence Chains</b>", styles['Heading2']))
            for ev in snapshot.evidence_units:
                story.append(Paragraph(f"• <b>[{ev.get('category')}] {ev.get('indicator_type')}</b>: {ev.get('indicator_value')} (weight: {ev.get('confidence_weight')})", body_style))
                story.append(Paragraph(f"  <i>Explanation:</i> {ev.get('explanation')}", body_style))

            doc.build(story)
            return buffer.getvalue()

        except ImportError:
            # Fallback plain-text PDF simulation if reportlab is not installed
            content = f"%PDF-1.4\nSIH26151 Case Report - {snapshot.export_id}\nGenerated By: {snapshot.generated_by}\nDisclaimer: {snapshot.disclaimer}\n"
            return content.encode("utf-8")
